// ── UI strings ───────────────────────────────────────────────
// Every word the interface shows lives here, keyed, so a second language is
// a second table and not a rewrite (the user's fork 3: English now, the seam
// kept). Card faces carry no text at all, so nothing in here touches them.
// Rulebook prose comes from RULES.md, not from this file.

export const STRINGS = {
  en: {
    nav: { learn: 'Learn', cards: 'Cards', play: 'Play', balance: 'Balance' },
    footer: { version: 'v0.1.0' },
    common: {
      loading: 'Loading the cards',
      loadFail: 'The card data did not load. Serve the folder over HTTP (make serve) and reload.',
      close: 'Close',
      print: 'Print',
      copied: 'Copied',
      placeholder: 'placeholder art',
      sayIt: 'Say it out loud',
    },
    cards: {
      title: 'The cards',
      lead: 'Ninety-four cards, poker size, no words on any of them. The picture is the name, the corners carry the numbers. Tap a card to see what it does.',
      printAll: 'Print all 94 (11 sheets)',
      printDeck: 'Print this deck',
      printing: 'Filling the print sheet',
      paper: 'Paper',
      a4: 'A4',
      letter: 'Letter',
      backs: { _: 'Card backs', none: 'no backs', few: '4 backs', all: 'a back per card' },
      filterAll: 'All decks',
      copies: 'copies',
      deck: { attack: 'Attack', skill: 'Skills', class: 'Classes', advantage: 'Advantage', boss: 'Bosses', biome: 'Biomes', life: 'Life', mode: 'Gentle mode', aid: 'Player aids' },
      corner: { bet: 'Bet', check: 'Check', tier: 'Tier', damage: 'Damage', actions: 'Actions', element: 'Element', class: 'Class', effect: 'Effect', passive: 'Passive', size: 'Size', life: 'Life cards', rage: 'Rage from round', rule: 'Rule', value: 'Worth', copies: 'Copies', icon: 'Glyph' },
      check: { none: 'always lands', sure: 'Sure, 75%', even: 'Even, 50%', hard: 'Hard, 25%', wild: 'Wild, 15%' },
      sort: { _: 'Sort by', deck: 'Deck', element: 'Element', tier: 'Tier', class: 'Class', check: 'Risk', damage: 'Damage', name: 'Name' },
      element: { _: 'Element', all: 'Any element', none: 'Yours' },
      tier: { _: 'Tier', all: 'Any tier' },
      klass: { _: 'Class', all: 'Any class', none: 'Open to all' },
      showBacks: 'Show backs',
      showFaces: 'Show faces',
      reset: 'Clear filters',
      empty: 'No card matches those filters.',
      face: 'Face',
      back: 'Back',
      printOrder: 'Printing always uses the boxed order, whatever this list is sorted by.',
    },
    learn: {
      heroKicker: 'A print-and-play boss rush for one player',
      heroTitle: 'Balance your <em>attack</em> and your <em>defense</em>.',
      heroLead: 'Build the boss out of bricks. Play your hero as a figure. Spend cards to attack, keep cards to defend, and do not be greedy. One die, ninety-four cards, and the toys already on the table.',
      ctaPlay: 'Play on screen',
      ctaCards: 'Print the cards',
      ctaFirst: 'First Game: one boss, three cards',
      walkthroughKicker: 'How it plays',
      rulebookTitle: 'The rulebook',
      rulebookLead: 'The complete rules, the same text that ships with the cards. About ten minutes to read.',
      bridgeTitle: 'Any die you own',
      bridgeLead: 'Find your row. Roll. Meet or beat the number. Three d6 track a d20 within 1.2 points at every step.',
      step: 'Step',
      odds: 'Odds',
      prev: 'Back',
      next: 'Next',
      slideOf: 'of',
      contents: 'Contents',
      deckHint: 'Arrow keys, or swipe.',
      slide: { dice: 'Any die you own', rulebook: 'The rulebook' },
    },
    play: {
      title: 'Play',
      setupTitle: 'Set up your run',
      firstGame: 'First Game',
      firstGameLead: 'Level 1 only, with Strike, Focus and All In. No classes, no skills, no Advantage. The whole game is already in those three cards.',
      fullRun: 'Full run',
      fullRunLead: 'Five bosses. Classes after the first, a new skill after every level, Advantage cards along the way.',
      element: 'Your element',
      die: 'Your die',
      mode: 'Mode',
      story: 'Story', standard: 'Standard', nightmare: 'Nightmare',
      modeHint: { story: 'one rung easier, for a first run or a younger player', standard: 'the table as printed', nightmare: 'one rung harder' },
      start: 'Start',
      resume: 'Resume run',
      abandon: 'Abandon run',
      level: 'Level',
      round: 'Round',
      boss: 'Boss',
      hero: 'You',
      minion: 'Minion',
      ready: 'Ready', spent: 'Spent', broken: 'Broken',
      actionsLeft: 'actions left',
      target: 'Target',
      body: 'the boss',
      bet: 'Bet',
      betHint: 'Pick how many Ready cards to stake.',
      needActions: 'needs 2 actions and your turn has fewer left',
      needBet: 'needs a Ready life card to bet',
      roll: 'Roll',
      typeRoll: 'or type your roll',
      need: 'need',
      hit: 'Hit!', miss: 'Miss',
      endTurn: 'End turn',
      bossTurn: 'Boss acts',
      bossRoll: 'The boss rolls',
      hide: 'Hide', move: 'Move',
      hideHint: 'Free with a Strike: the next hit this round is halved.',
      hidden: 'Hidden',
      rage: 'RAGE. Double damage, no guard.',
      rageSoon: 'Rage next round.',
      won: 'The boss falls!',
      lost: 'You are Down.',
      runWon: 'You cleared all five levels.',
      nextLevel: 'Next level',
      newRun: 'New run',
      pickClass: 'Choose your class',
      draftTitle: 'Pick one skill',
      draftLead: 'Three revealed, keep one.',
      advDraw: 'You draw an Advantage card',
      advHand: 'Advantage',
      playAdv: 'Play',
      useRune: 'Use the Rune on this check',
      reroll: 'Hunter: reroll',
      knight: 'Knight guard used',
      barrierPrompt: 'Play Barrier to cancel this?',
      letItHappen: 'Let it happen',
      log: 'Log',
      logShow: 'Show the log', logHide: 'Hide the log',
      // The boss speaks above its own head instead of in the log
      bossWatch: 'The boss watches you.',
      aimedAtYou: 'aimed at you',
      aimedAtAlly: 'aimed at your Ally',
      unguardable: 'unguardable',
      // The gear shelf: what you already have in play
      shelf: 'In play',
      relic: 'Relic', rune: 'Rune', bubbleSlot: 'Bubble',
      // The number is ALLY_DEF in game/engine.js, not a word in here: the
      // rulebook can change it and this string must not have to be found.
      ally: 'Ally', allyDef: 'defense',
      allyGone: 'The Ally is gone.',
      cover: 'Cover the Ally',
      coverHint: 'Take the hit yourself, whole, and the Ally stays.',
      slotEmpty: 'empty',
      // The three bands of the action panel
      bandCards: 'Your cards', bandGo: 'Resolve',
      pickHint: 'the die is waiting',
      placeholderNote: 'Enemies and heroes are placeholders drawn from bricks. The real art comes later.',
      // Second Wind, the gentle-mode card
      secondWind: 'Second Wind',
      secondWindHint: 'A safety net. The first comeback each level is free, then the roll climbs: Sure, Even, Hard, Wild. You come back with 2 Broken cards standing.',
      down: 'You are Down',
      downFree: 'Your first comeback this level is free.',
      downLadder: 'The comeback needs',
      reviveTry: 'Take the comeback',
      reviveGiveUp: 'Let the level end',
      // The plan lane
      plan: 'Your turn',
      planHint: 'Click a card once for each action you want it to take. Click a number to drop that step.',
      planEmpty: 'Pick a card. Three actions this turn.',
      resolvePlan: 'Resolve the turn',
      clearPlan: 'Clear',
      planStep: 'Step',
      reaction: 'Reaction',
      reactionHint: 'Barrier waits here for the boss to act.',
      attachTo: 'attached to step',
      tooManyActions: 'That is more than the actions left this turn.',
      notEnoughReady: 'By that step there is no Ready card left to bet.',
      keys: '1 to 9 pick a card · Enter resolves · Backspace undoes',
      // The rest of the table, shown but not played
      table: 'On the table',
      drawPile: 'Skills',
      advPile: 'Advantage',
      extraPile: 'Extra lives',
      biomeCard: 'Biome',
      bossPile: 'Boss life',
      faceDown: 'face down',
      inTheBox: 'in the box',
    },
    balance: {
      title: 'Balance',
      lead: 'The same engine the runner uses, played thousands of times by four stand-in styles. The published table in BALANCE.md comes from tools/sim.py at 20,000 fights per cell; this one is for trying things.',
      trials: 'Fights per cell',
      bonus: 'Affinity bonus',
      run: 'Run',
      running: 'Running',
      stop: 'Stop',
      style: { turtle: 'turtle', safe: 'safe', adaptive: 'adaptive', gamble: 'gamble' },
      cols: { level: 'Level', win: 'win', rounds: 'rounds', broken: 'broken' },
      legacy: 'Match tools/sim.py exactly',
      legacyHint: 'Reproduces three simplifications the Python simulator makes (Brace never halves, Summon moves a flat 100, Roar flattens the next check to Even) so its table can be checked. Off, the engine plays the rulebook.',
      advantage: 'Advantage deck',
      klass: 'Class',
      none: 'none',
    },
  },
};

let lang = 'en';
export function setLang(l) { if (STRINGS[l]) lang = l; }
export function getLang() { return lang; }

/** t('play.start') -> 'Start'. Missing keys return the key, loudly. */
export function t(path) {
  const v = path.split('.').reduce((o, k) => (o && o[k] !== undefined ? o[k] : undefined), STRINGS[lang]);
  return v === undefined ? `[${path}]` : v;
}
